import assert from "node:assert/strict";
import { EMPTY_ACTION_SNAPSHOT } from "../src/actions.ts";
import { PUCK_RADIUS, PUCK_SPEED_CAP, RINK, STRIKER_IMPULSE_SPEED_CAP, STRIKER_MAX_SPEED, STRIKER_RADIUS } from "../src/constants.ts";
import { stepGame } from "../src/physics.ts";
import { DEFAULT_MATCH_SETTINGS, goalBounds, incompatibleGoalPlayers, minimumPlayableGoalSize, normalizeMatchSettings, puckRadius, puckSpeedCap, returnSpeedCap, settingsSummary, strikerImpulseCap, strikerRadius, strikerSpeedCap } from "../src/settings.ts";
import { createInitialGameState, type HockeyGameState } from "../src/state.ts";

const requested = (settings = DEFAULT_MATCH_SETTINGS) => Object.freeze({ ...EMPTY_ACTION_SNAPSHOT, settingsRequested: settings });
const changed = normalizeMatchSettings({ puckSpeed: 130, puckSize: 125, pawSpeed: { 1: 70, 2: 130 }, pawSize: { 1: 75, 2: 125 }, goalSize: { 1: 75, 2: 125 } });
assert.deepEqual(DEFAULT_MATCH_SETTINGS, { puckSpeed: 75, pawSpeed: { 1: 75, 2: 75 }, returnSpeed: { 1: 75, 2: 75 }, puckSize: 125, pawSize: { 1: 125, 2: 125 }, goalSize: { 1: 125, 2: 125 } });
assert.equal(puckRadius(DEFAULT_MATCH_SETTINGS), PUCK_RADIUS * 1.25);
assert.equal(strikerRadius(DEFAULT_MATCH_SETTINGS, 1), STRIKER_RADIUS * 1.25);
assert.equal(puckSpeedCap(DEFAULT_MATCH_SETTINGS), PUCK_SPEED_CAP * 0.75);
assert.equal(returnSpeedCap(DEFAULT_MATCH_SETTINGS, 1), PUCK_SPEED_CAP * 0.75 * 0.75);
assert.equal(strikerSpeedCap(DEFAULT_MATCH_SETTINGS, 2), STRIKER_MAX_SPEED * 0.75);
assert.equal(strikerImpulseCap(DEFAULT_MATCH_SETTINGS, 1), STRIKER_IMPULSE_SPEED_CAP * 0.75);
assert.deepEqual(goalBounds(DEFAULT_MATCH_SETTINGS, 1), { left: 155, right: 385 });
assert.equal(puckRadius(changed), 28.75);
assert.equal(strikerRadius(changed, 1), 33.75);
assert.ok(Math.abs(strikerSpeedCap(changed, 1) - 1855) < 0.001);
assert.ok(Math.abs(strikerImpulseCap(changed, 2) - 2925) < 0.001);
assert.equal(goalBounds(changed, 1).right - goalBounds(changed, 1).left, 138);
assert.equal(goalBounds(changed, 2).right - goalBounds(changed, 2).left, 230);
assert.deepEqual(normalizeMatchSettings({ puckSpeed: 999 }), normalizeMatchSettings({ puckSpeed: 130 }));
assert.equal(normalizeMatchSettings({ puckSize: 1 }).puckSize, 25);
assert.equal(normalizeMatchSettings({ puckSize: 999 }).puckSize, 200);
assert.equal(normalizeMatchSettings({ puckSpeed: 1 }).puckSpeed, 70);
assert.deepEqual(normalizeMatchSettings({ ...changed, returnSpeed: { 1: 70, 2: 130 } }).returnSpeed, { 1: 70, 2: 130 });
assert.equal(normalizeMatchSettings(changed).returnSpeed[1], 75);
assert.equal(settingsSummary(DEFAULT_MATCH_SETTINGS), "Normal settings");
assert.match(settingsSummary(normalizeMatchSettings({ returnSpeed: { 1: 70, 2: 75 } })), /P1: 75% paw speed .* 70% return/);
assert.equal(minimumPlayableGoalSize(25), 30);
assert.equal(minimumPlayableGoalSize(125), 55);
assert.equal(minimumPlayableGoalSize(200), 75);
const incompatible = normalizeMatchSettings({ puckSize: 200, goalSize: { 1: 25, 2: 200 } });
assert.deepEqual(incompatibleGoalPlayers(incompatible), [1]);
assert.deepEqual(incompatibleGoalPlayers(DEFAULT_MATCH_SETTINGS), []);

let ready = stepGame(createInitialGameState(), requested(changed), 1 / 60);
assert.deepEqual(ready.activeMatchSettings, changed);
assert.deepEqual(ready.pendingMatchSettings, changed);
let playing = { ...ready, phase: "playing" as const } as HockeyGameState;
playing = stepGame(playing, requested(DEFAULT_MATCH_SETTINGS), 1 / 60);
assert.deepEqual(playing.activeMatchSettings, changed);
assert.deepEqual(playing.pendingMatchSettings, DEFAULT_MATCH_SETTINGS);
const goal = { ...playing, phase: "goal" as const, phaseTimer: 0 } as HockeyGameState;
const afterGoal = stepGame(goal, EMPTY_ACTION_SNAPSHOT, 1 / 60);
assert.deepEqual(afterGoal.activeMatchSettings, DEFAULT_MATCH_SETTINGS);
assert.equal(afterGoal.phase, "countdown");
console.log(JSON.stringify({ schema: "cat-air-hockey.settings@1", passed: true, checks: 30 }, null, 2));
